### ISSUE TITLE
1.1.4版本初始化异常

### ISSUE THREAD

**Issue by Jermmy** [LuckyJayce/ViewPagerIndicator#33]
我切换成1.1.4版本后，初始化时抛出NullPointerException
关键代码：
``` indicatorView = (ScrollIndicatorView) findViewById(R.id.indicator); 
        viewPager = (ViewPager) findViewById(R.id.viewpager);
        indicatorViewPager = new IndicatorViewPager(indicatorView, viewPager);
        indicatorView.setScrollBar(new ColorBar(this, Color.BLUE, 5));
        indicatorViewPager.setPageOffscreenLimit(2);
```
异常：
```
java.lang.NullPointerException
at com.shizhefei.view.indicator.FixedIndicatorView.measureScrollBar(FixedIndicatorView.java:499)
at com.shizhefei.view.indicator.FixedIndicatorView.onSizeChanged(FixedIndicatorView.java:564)
at android.view.View.sizeChange(View.java:14993)
at android.view.View.setFrame(View.java:14966)
at android.view.View.layout(View.java:14874)
at android.view.ViewGroup.layout(ViewGroup.java:4655)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.HorizontalScrollView.onLayout(HorizontalScrollView.java:1474)
at com.shizhefei.view.indicator.ScrollIndicatorView.onLayout(ScrollIndicatorView.java:188)
at android.view.View.layout(View.java:14878)
at android.view.ViewGroup.layout(ViewGroup.java:4655)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
at android.view.View.layout(View.java:14878)
at android.view.ViewGroup.layout(ViewGroup.java:4655)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
at android.view.View.layout(View.java:14878)
at android.view.ViewGroup.layout(ViewGroup.java:4655)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
at android.view.View.layout(View.java:14878)
at android.view.ViewGroup.layout(ViewGroup.java:4655)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14878)
at android.view.ViewGroup.layout(ViewGroup.java:4655)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
at android.view.View.layout(View.java:14878)
at android.view.ViewGroup.layout(ViewGroup.java:4655)
....
```

**Comment by LuckyJayce** [comment]
Adapter 没设置？

**Comment by Jermmy** [comment]
没有，我是从网络获取数据后才添加Adapter的

**Comment by LuckyJayce** [comment]
你之前版本多少？
先设置适配器试下，可以适配器notifydatachange啊

**Comment by Jermmy** [comment]
之前的版本是1.0.7

**Comment by AcgnCodeMonkey** [comment]
@LuckyJayce 这个初始化问题希望能修复一下，项目使用了MVP，不方便在一开始就初始化适配器，目前是这么写的 indicatorViewPager.setAdapter(new TabFragmentAdapter(((CarListTablePresenter) presenter).getSupportFragmentManager(),
                presenter.exposeContext(), new String[]{}, new ArrayList<Fragment>()));

**Comment by wudifamo** [comment]
我也遇到了这个问题,1.0.6升级1.1.4版本,需要从后台拿到tabs之后才能确定adapter中的数据,直接就崩了

**Comment by LuckyJayce** [comment]
v1.1.5可以一开始不设置adapter
