### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference

### ISSUE THREAD

**Issue by leibown** [LuckyJayce/ViewPagerIndicator#35]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
at android.support.v4.app.FragmentManagerImpl.getFragment(FragmentManager.java:682)
at com.shizhefei.view.indicator.FragmentListPageAdapter.restoreState(FragmentListPageAdapter.java:203)
at android.support.v4.view.ViewPager.onRestoreInstanceState(ViewPager.java:1448)
at android.view.View.dispatchRestoreInstanceState(View.java:13788)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2889)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2897)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2897)
at android.view.View.restoreHierarchyState(View.java:13766)
at android.support.v4.app.Fragment.restoreViewState(Fragment.java:475)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1131)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:532)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5601)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

请问是什么问题？

**Comment by CoderAstro** [comment]
哥们,你解决了吗,我也遇到了

**Comment by leibown** [comment]
我解决了，但是不是这个框架的问题，是因为我原来Fragment做了单例启动模式，然后第二次启动这个 Fragment时不会调用onCreate方法，因为在内存中已经存在了这个Fragment的对象，然后这个界面中的List集合其实是被销毁了，所以这个时候会报这个错误，希望能帮到你，如果我解释得不够清楚，可以直接给我发邮件leibown.leila@gmail.com

**Comment by akgup** [comment]
@leibown  thanks, man it helped me to solve my problem also. Though i don't understand Chinese but google translator helped me.
