### ISSUE TITLE
        java.lang.NullPointerException: Attempt to invoke interface method 'void com.shizhefei.view.indicator.Indicator.setItemClickable(boolean)' on a null object reference

### ISSUE THREAD

**Issue by lk6233160** [LuckyJayce/ViewPagerIndicator#41]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.shizhefei.view.indicator.Indicator.setItemClickable(boolean)' on a null object reference
                                                                    at com.shizhefei.view.indicator.IndicatorViewPager.<init>(IndicatorViewPager.java:50)
                                                                    at com.shizhefei.view.indicator.IndicatorViewPager.<init>(IndicatorViewPager.java:43)

**Comment by LuckyJayce** [comment]
你布局findById Indicator是空的
