### ISSUE TITLE
NullPointException一直没发现这个问题在哪里

### ISSUE THREAD

**Issue by TPwaiwai** [LuckyJayce/ViewPagerIndicator#43]
java.lang.NullPointerException
                                                                        at com.shizhefei.view.indicator.FragmentListPageAdapter.instantiateItem(FragmentListPageAdapter.java:139)
                                                                        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1182)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:681)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
                                                                        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2176)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1874)
                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1089)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1265)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4357)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:532)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                                        at android.os.Handler.handleCallback(Handler.java:725)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by TPwaiwai** [comment]
public class TabActivity extends AppCompatActivity implements View.OnClickListener {


    private FixedIndicatorView tab_main_indicator;
    private SViewPager tab_main_viewPager;
    private int[] tabIcons = {R.drawable.select_home, R.drawable.select_plate, R.drawable.button01, R.drawable.select_mall,
            R.drawable.select_me};
    private SparseArray<Fragment> navigateMap = new SparseArray<>();
    private Tab1Fragment tab1Fragment;
    private Tab2Fragment tab2Fragment;
    private Tab3Fragment tab3Fragment;
    private Tab4Fragment tab4Fragment;
    private IndicatorViewPager indicatorViewPager;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tab);
        EventBus.getDefault().register(this);
        tab_main_indicator = ((FixedIndicatorView) findViewById(R.id.tab_main_indicator));
        tab_main_viewPager = ((SViewPager) findViewById(R.id.tab_main_viewPager));
        indicatorViewPager = new IndicatorViewPager(tab_main_indicator, tab_main_viewPager);
        MyAdapter adapter = new MyAdapter(getSupportFragmentManager());
        indicatorViewPager.setAdapter(adapter);
        // 禁止viewpager的滑动事件
        tab_main_viewPager.setCanScroll(false);
        tab_main_viewPager.setOffscreenPageLimit(tabIcons.length);
        // 设置viewpager保留界面不重新加载的页面数量
        indicatorViewPager.setCurrentItem(0, false);
    }


    private Fragment getFragment(int position) {
        Fragment fragment = navigateMap.get(position);
        if (fragment != null) {
            return fragment;
        }
        switch (position) {
            case 0:
                tab1Fragment = new Tab1Fragment();
                break;
            case 1:
                tab2Fragment = new Tab2Fragment();
                break;
            case 2:
                tab3Fragment = new Tab3Fragment();
                break;
            case 3:
                tab4Fragment = new Tab4Fragment();
                break;
        }
        navigateMap.put(position, fragment);
        return fragment;
    }


    @Override
    public void onClick(View v) {
        switch (v.getId()) {

        }

    }


    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onEvent(Integer integer) {
        switch (integer) {
            case Event.GO_TAB1:
                Log.i("lenovoInfom", "onEvent: " + integer);
                break;
        }

    }

    private class MyAdapter extends IndicatorViewPager.IndicatorFragmentPagerAdapter {
        private LayoutInflater inflater;

        public MyAdapter(FragmentManager fragmentManager) {
            super(fragmentManager);
            inflater = LayoutInflater.from(getApplicationContext());
        }

        @Override
        public int getCount() {
            return tabIcons.length;
        }

        @Override
        public View getViewForTab(int position, View convertView, ViewGroup container) {
            if (convertView == null) {
                convertView = inflater.inflate(R.layout.tab_main, container, false);
            }
            ImageView imageView = (ImageView) convertView;
            imageView.setImageDrawable(getResources().getDrawable(tabIcons[position]));
            AutoUtils.auto(imageView);
            return imageView;
        }

        @Override
        public Fragment getFragmentForPage(int position) {
            return getFragment(position);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(this);
    }
}

**Comment by LuckyJayce** [comment]
你adapter的count等于5，但是你getFragmentForPage  在posistion为4的时候返回null

**Comment by TPwaiwai** [comment]
谢谢，问题解决了，自己的失误****
